#!/bin/bash
server_addr=$1
db_username=$2
db_password=$3

#server_addr="jdbc:oracle:thin:@//db.dm.bionta.com:1521/social"
#db_username="dongliang"
#db_password="123456"

db_table_name="r_people"
hbase_namespace="sadan3"
hbase_table_name="r_people"
column_family="basic"

# echo "create_namespace 'sadan3';quit;" | hbase shell

sqoop import \
-D sqoop.hbase.add.row.key=true \
--connect ${server_addr} \
--username ${db_username} \
--password ${db_password} \
--query "SELECT '兰州市' AS REGION, CAST(ID AS VARCHAR2(50)) AS SID, DISTRICTID, DISTRICTNAME, ORGID, ORGNAME, STREETID, STREETNAME, CODENUMERIC, NAME, ENGLISHNAME, FORMERNAME, CARDNO, ISSORGAN, ISSDATE, REGIONID, REGIONNAME, CARDTYPEID, CARDTYPENAME, CERTIFICATEID, GENDER, BIRTHDAY, PLACEOFBIRTH, NATIONID, NATIONNAME, NATIVEPLACE, HEIGHT, BLOODID, BLOODNAME, POLITICSID, POLITICSNAME, EDULEVELID, EDULEVELNAME, HEALTHID, HEALTHNAME, MARRYID, MARRYNAME, MARRIEDTYPEID, MARRIEDTYPENAME, MILITARYSERVICEID, MILITARYSERVICENAME, FAITHID, FAITHNAME, WORKSTATUSID, WORKSTATUSNAME, SOCIALPOSITION, SPECIALTY, REGISTERTYPEID, REGISTERTYPENAME, THEREASONOFNOTMOVE, RACODE, RASTATUS, RAADDRESS, RESIDEADDRESS, TEL, SERVICESPACE, JOINWORK, PROFESSION, COMPANYNATURE, COMPANYINDUSTRY, GOVERJOB, SKILL, COMPANYJOB, SOCIALJOB, CELLPHONENUMBER, EMAIL, PHOTO, TOHERETIME, WHERETOHERE, MOVETOTIME, MOVETOWHERE, MOVENO, MOVEREASON, MOVETYPE, REGISTER, WFID, DATELEVEL, ATTRIBUTESTR, REMARK, CREATEUSER, CREATETIME, UPDATEUSER, UPDATETIME, VERSION, DF1, DF2, DF3, DF4, DF5, DF6, DF7, DF8, DF9, DF10, FIRSTMARRDATE, PARTYJOINDATE, WORKUNITS, RETIREMENTTIME, ISFLOWPEOPLE, STAYLENGTH, STATE, DATASOURCE, STATEREASON, FAMILYID, ISLIVEHERE, FAMILYSTATE, DF11 FROM ${db_table_name}  where \$CONDITIONS" \
-m 1  \
--hbase-table ${hbase_namespace}:${hbase_table_name} \
--column-family ${column_family} \
--hbase-create-table \
--hbase-row-key REGION,SID

hive -e "CREATE DATABASE IF NOT EXISTS ${hbase_namespace}; 
DROP TABLE IF EXISTS ${hbase_namespace}.${hbase_table_name}; 
CREATE EXTERNAL TABLE ${hbase_namespace}.${hbase_table_name}(HBASE_ROWKEY STRING,ID STRING, DISTRICTID BIGINT, DISTRICTNAME STRING, ORGID BIGINT, ORGNAME STRING, 
STREETID BIGINT, STREETNAME STRING, CODENUMERIC STRING, NAME STRING, ENGLISHNAME STRING, FORMERNAME STRING, CARDNO STRING, ISSORGAN STRING, ISSDATE TIMESTAMP, 
REGIONID BIGINT, REGIONNAME STRING, CARDTYPEID BIGINT, CARDTYPENAME STRING, CERTIFICATEID STRING, GENDER STRING, BIRTHDAY TIMESTAMP, PLACEOFBIRTH STRING, 
NATIONID BIGINT, NATIONNAME STRING, NATIVEPLACE STRING, HEIGHT BIGINT, BLOODID BIGINT, BLOODNAME STRING, POLITICSID BIGINT, POLITICSNAME STRING, EDULEVELID BIGINT,
EDULEVELNAME STRING, HEALTHID BIGINT, HEALTHNAME STRING, MARRYID BIGINT, MARRYNAME STRING, MARRIEDTYPEID BIGINT, MARRIEDTYPENAME STRING, MILITARYSERVICEID BIGINT,
MILITARYSERVICENAME STRING, FAITHID BIGINT, FAITHNAME STRING, WORKSTATUSID BIGINT, WORKSTATUSNAME STRING, SOCIALPOSITION STRING, SPECIALTY STRING, REGISTERTYPEID BIGINT,
REGISTERTYPENAME STRING, THEREASONOFNOTMOVE STRING, RACODE STRING, RASTATUS STRING, RAADDRESS STRING, RESIDEADDRESS STRING, TEL STRING, SERVICESPACE STRING,
JOINWORK TIMESTAMP, PROFESSION STRING, COMPANYNATURE STRING, COMPANYINDUSTRY STRING, GOVERJOB STRING, SKILL STRING, COMPANYJOB STRING, SOCIALJOB STRING,
CELLPHONENUMBER STRING, EMAIL STRING, PHOTO STRING, TOHERETIME TIMESTAMP, WHERETOHERE STRING, MOVETOTIME TIMESTAMP, MOVETOWHERE STRING, MOVENO STRING,
MOVEREASON STRING, MOVETYPE STRING, REGISTER STRING, WFID STRING, DATELEVEL STRING, ATTRIBUTESTR STRING, REMARK STRING, CREATEUSER STRING, CREATETIME TIMESTAMP,
UPDATEUSER STRING, UPTIMESTAMP TIMESTAMP, VERSION BIGINT, DF1 STRING, DF2 STRING, DF3 STRING, DF4 STRING, DF5 STRING, DF6 STRING, DF7 STRING, DF8 STRING, DF9 STRING,
DF10 STRING, FIRSTMARRDATE TIMESTAMP, PARTYJOINDATE TIMESTAMP, WORKUNITS STRING, RETIREMENTTIME TIMESTAMP, ISFLOWPEOPLE STRING, STAYLENGTH BIGINT, STATE STRING,
DATASOURCE STRING, STATEREASON STRING, FAMILYID BIGINT, ISLIVEHERE STRING, FAMILYSTATE STRING, DF11 STRING) 
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler' 
WITH SERDEPROPERTIES(\"hbase.columns.mapping\"=\":key, ${column_family}:SID,${column_family}:DISTRICTID, ${column_family}:DISTRICTNAME,
${column_family}:ORGID, ${column_family}:ORGNAME, ${column_family}:STREETID, ${column_family}:STREETNAME, ${column_family}:CODENUMERIC,
${column_family}:NAME, ${column_family}:ENGLISHNAME, ${column_family}:FORMERNAME, ${column_family}:CARDNO, ${column_family}:ISSORGAN,
${column_family}:ISSDATE, ${column_family}:REGIONID, ${column_family}:REGIONNAME, ${column_family}:CARDTYPEID, ${column_family}:CARDTYPENAME,
${column_family}:CERTIFICATEID, ${column_family}:GENDER, ${column_family}:BIRTHDAY, ${column_family}:PLACEOFBIRTH, ${column_family}:NATIONID,
${column_family}:NATIONNAME, ${column_family}:NATIVEPLACE, ${column_family}:HEIGHT, ${column_family}:BLOODID, ${column_family}:BLOODNAME,
${column_family}:POLITICSID, ${column_family}:POLITICSNAME, ${column_family}:EDULEVELID, ${column_family}:EDULEVELNAME, ${column_family}:HEALTHID,
${column_family}:HEALTHNAME, ${column_family}:MARRYID, ${column_family}:MARRYNAME, ${column_family}:MARRIEDTYPEID, ${column_family}:MARRIEDTYPENAME, 
${column_family}:MILITARYSERVICEID, ${column_family}:MILITARYSERVICENAME, ${column_family}:FAITHID, ${column_family}:FAITHNAME, ${column_family}:WORKSTATUSID, 
${column_family}:WORKSTATUSNAME, ${column_family}:SOCIALPOSITION, ${column_family}:SPECIALTY, ${column_family}:REGISTERTYPEID, ${column_family}:REGISTERTYPENAME, 
${column_family}:THEREASONOFNOTMOVE, ${column_family}:RACODE, ${column_family}:RASTATUS, ${column_family}:RAADDRESS, ${column_family}:RESIDEADDRESS, 
${column_family}:TEL, ${column_family}:SERVICESPACE, ${column_family}:JOINWORK, ${column_family}:PROFESSION, ${column_family}:COMPANYNATURE, ${column_family}:COMPANYINDUSTRY,
${column_family}:GOVERJOB, ${column_family}:SKILL, ${column_family}:COMPANYJOB, ${column_family}:SOCIALJOB, ${column_family}:CELLPHONENUMBER, ${column_family}:EMAIL,
${column_family}:PHOTO, ${column_family}:TOHERETIME, ${column_family}:WHERETOHERE, ${column_family}:MOVETOTIME, ${column_family}:MOVETOWHERE, ${column_family}:MOVENO,
${column_family}:MOVEREASON, ${column_family}:MOVETYPE, ${column_family}:REGISTER, ${column_family}:WFID, ${column_family}:DATELEVEL, ${column_family}:ATTRIBUTESTR,
${column_family}:REMARK, ${column_family}:CREATEUSER, ${column_family}:CREATETIME, ${column_family}:UPDATEUSER, ${column_family}:UPTIMESTAMP, ${column_family}:VERSION,
${column_family}:DF1, ${column_family}:DF2, ${column_family}:DF3, ${column_family}:DF4, ${column_family}:DF5, ${column_family}:DF6, ${column_family}:DF7, ${column_family}:DF8,
${column_family}:DF9, ${column_family}:DF10, ${column_family}:FIRSTMARRDATE, ${column_family}:PARTYJOINDATE, ${column_family}:WORKUNITS, ${column_family}:RETIREMENTTIME,
${column_family}:ISFLOWPEOPLE, ${column_family}:STAYLENGTH, ${column_family}:STATE, ${column_family}:DATASOURCE, ${column_family}:STATEREASON, ${column_family}:FAMILYID,
${column_family}:ISLIVEHERE, ${column_family}:FAMILYSTATE, ${column_family}:DF11\") 
TBLPROPERTIES(\"hbase.table.name\" = \"${hbase_namespace}:${hbase_table_name}\")"

